[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ligotools"
version = "0.1.0"
description = "LIGO utilities for STAT 159/259 HW2"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["ligotools*"]
